### ISSUE TITLE
Security: Please set container Security Context on all Containers

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1098]
Many companies have a security requirement in place that all containers must have a read-only file system and not allow privileged escalation.  Please set this (Or allow it to be set) on all containers.  This would mean either adding it yourself or adding it to any CRDs that end up creating containers so the user can set it.  Note this is at the container level, not the pod level.  I have created a separate feature request for the pod security content.

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

See the pod security context example below for what is required to be set.
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
  - name: sec-ctx-demo
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
```

Related Feature Request: https://github.com/knative/eventing/issues/2882
