### ISSUE TITLE
Operations: Please allow setting nodeSelector, tolerations, and affinity on all Pods

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1099]
Most companies with complex enough kubernetes deployments that have multiple different node groups require some sort of topology selection so pods will run on the correct group of nodes.  Please allow setting nodeSelector, tolerations, and affinity on all Pods to accomplish this.  This includes adding it to any CRDs that create pods so these values are settable.

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

See below for example:
```
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  nodeSelector:
    disktype: sad
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```

Related Feature Request: https://github.com/knative/eventing/issues/2883
