### ISSUE TITLE
Multitenant GitHubsource

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1131]
I'm opening this issue to start discussing on how to make the GitHubSource adapter multi-tenant.

Following is a plan based on the all various discussions I had on this topic:
- Keep using ksvc for push-based autoscaling
- Make the ksvc private (no public IP)
- Move the ksvc to the system-namespace
- Ideally create a public route. However this is not possible today to create cross-namespace routes (route in ns1 pointing to revision in ns2). So instead create an `ingresses.networking.internal.knative.dev` object in the same namespace as the GitHubSource CR. See example below.
- Use the `host` header to select the proper GitHubSource configuration (common practice). Then after is same as before.

The multi-tenant adapter needs to cache the mapping between host to GitHubSource CR. Usually we do this by having each adapter instance watching all CRs they care about and updating their internal cache. That's fine to get started but I don't think this model scales well. That's a separate, orthogonal discussion.

Here an example of a cross-namespace ingress (istio):

```yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: Ingress
metadata:
  annotations:
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev 
  name: route2
spec:
  rules:
    - hosts:
        - route2.examples-mtksvc-tenant.svc.cluster.local
        - route2.examples-mtksvc-tenant.kube-dev.us-south.containers.appdomain.cloud
      http:
        paths:
          - retries:
              attempts: 3
              perTryTimeout: 10m0s
            splits:
              - appendHeaders:
                  Knative-Serving-Namespace: examples-mtksvc
                  Knative-Serving-Revision: print-host-t7hs5
                percent: 100
                serviceName: print-host-t7hs5
                serviceNamespace: examples-mtksvc
                servicePort: 80
            timeout: 10m0s
      visibility: ExternalIP
  visibility: ExternalIP
```
