### ISSUE TITLE
KafkaSource broken

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#1143]
**Describe the bug**

Applying `KAfkaSource` yaml does NOT work.

 **Expected behavior**

Applying `KAfkaSource` yaml actually works.. 

 **To Reproduce**

With 0.14, apply this:

```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knativerhdeveloperdemokafka
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: my-topic
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
```
you will get:

```
Error from server (BadRequest): error when creating "020-kafka-source.yml": admission webhook "defaulting.webhook.kafka.sources.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "apiVersion"
```

 **Knative release version**
* 0.14
* HEAD

 **Additional context**

This seems related:
* https://github.com/knative/eventing-contrib/pull/1107 

(works with 0.13.x release)

**Comment by matzew** [comment]
from the controller log:

```
{
  "level": "info",
  "ts": "2020-04-16T09:18:30.582Z",
  "logger": "kafka-controller",
  "caller": "webhook/admission.go:72",
  "msg": "Webhook ServeHTTP request=&http.Request{Method:\"POST\", URL:(*url.URL)(0xc0009e4d80), Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Accept\":[]string{\"application/json, */*\"}, \"Accept-Encoding\":[]string{\"gzip\"}, \"Content-Length\":[]string{\"2010\"}, \"Content-Type\":[]string{\"application/json\"}, \"User-Agent\":[]string{\"kube-apiserver-admission\"}}, Body:(*http.body)(0xc0005ed640), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:2010, TransferEncoding:[]string(nil), Close:false, Host:\"kafka-source-webhook.knative-eventing.svc:443\", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:\"192.168.122.172:32876\", RequestURI:\"/defaulting?timeout=30s\", TLS:(*tls.ConnectionState)(0xc00047d340), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc0005ed680)}"
}
{
  "level": "info",
  "ts": "2020-04-16T09:18:30.583Z",
  "logger": "kafka-controller",
  "caller": "webhook/admission.go:93",
  "msg": "AdmissionReview for v1.GroupVersionKind{Group:\"sources.knative.dev\", Version:\"v1alpha1\", Kind:\"KafkaSource\"}: default/kafka-source response=&v1beta1.AdmissionResponse{UID:\"\", Allowed:false, Result:(*v1.Status)(0xc000509900), Patch:[]uint8(nil), PatchType:(*v1beta1.PatchType)(nil), AuditAnnotations:map[string]string(nil)}",
  "knative.dev/kind": "sources.knative.dev/v1alpha1, Kind=KafkaSource",
  "knative.dev/namespace": "default",
  "knative.dev/name": "kafka-source",
  "knative.dev/operation": "CREATE",
  "knative.dev/resource": "sources.knative.dev/v1alpha1, Resource=kafkasources",
  "knative.dev/subresource": "",
  "knative.dev/userinfo": "{minikube-user  [system:masters system:authenticated] map[]}"
}
```

**Comment by matzew** [comment]
stupid me:

```
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display
```

was the fix ;-)
