### ISSUE TITLE
Vanity GitHub Webhook URL

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1171]
**Problem**
The MT githubsource controller generates webhook of the form `http://githubsource-adapter.knative-sources.<domain>/<ns>/<name>`

where `ns` and `name` corresponds the githubsource CR.

Instead it should generate webhook of the form `http://<name>.<ns>.<domain>`. 

**Context**
See https://github.com/knative/eventing-contrib/issues/1131#issuecomment-612559118 for more details. 

Depends on https://docs.google.com/document/d/1xK-g55kFdRRpYsiHyesmYWKURWi1sJlIWxMwkRmlyuM/edit#

/cc @dug @mattmoor

**Comment by duglin** [comment]
Ideally it should use the domainTemplate to generate the URL since the networking setup in the env might require a certain format.

**Comment by lionelvillard** [comment]
The plan is for the GitHub controller to generate an Kingress of the following form:

```yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: Ingress
metadata:
  annotations:
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev
  name: my-github-source
  namespace: tenant
spec:
  rules:
    - hosts:
        -  DomainNameFromTemplate(ctx, cr('mygithub-source'), 'mygithub-source')
      http:
        paths:
          - rewriteHost: github-adapter.svc.cluster.local
            appendHeaders:
              name: "my-github-source"
              namespace: "tenant"
      visibility: ExternalIP
  visibility: ExternalIP
```

Initially the domain template can be specified as an annotation on the GitHubSource CR and eventually we can add a ConfigMap in knative-sources where to specify the template. 

I don't think we want the GithubSource adapter to read the serving cm `config-network`. I would rather keep it separate for portability reason.    

@duglin @julz

Note: this will be an opt-in feature since it depends on Istio.
