### ISSUE TITLE
KafkaSource reports Invalid value for key-type

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#1274]
**Describe the bug**

```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-enriched
  namespace: debezium-knative-demo
  labels:
    kafkasources.sources.knative.dev/key-type: int
spec:
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - temperature-values-enriched
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
```
I get this log message in the controller:

```
"msg":"Invalid value for kafkasources.sources.knative.dev/key-type: int. Allowed: [string int float byte-array]"
```

not sure why `int` does not work here
