### ISSUE TITLE
Cannot use a third part Kafka instance as the Kafka Channel

### ISSUE THREAD

**Issue by ericshen881027** [knative/eventing-contrib#1322]
**Describe the bug**
I already setup a Kafka instance out of knative, I want to use this Kafka instance as the Kafka Channel, but I get the "ChannelReconcileFailed" Error message from the kafka-ch-controller.

 **Expected behavior**
I can directly use the existing Kafka instance instead of setup a new Kafka instance in the knative.

 **To Reproduce**
1. Install the KafkaChannel sub-component on my Knative Eventing cluster:
```
curl -L "https://storage.googleapis.com/knative-releases/eventing-contrib/previous/v0.13.0/kafka-channel.yaml"\
| sed 's/REPLACE_WITH_CLUSTER_URL/my-kafka-address:9092/' \
| kubectl apply --filename -
```

2. create the configMap config-kafka in the my namespace named "test-channel".
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka
  namespace: test-channel
data:
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers: my-kafka-address:9092
```
3. create the KafkaChannel
```
apiVersion: messaging.knative.dev/v1alpha1
kind: KafkaChannel
metadata:
  name: my-kafka-channel
  namespace: test-channel
  annotations:
    eventing.knative.dev/scope: namespace
spec:
  numPartitions: 1
  replicationFactor: 1
```
4. I get the following error:
```
Events:
  Type     Reason                  Age                 From                 Message
  ----     ------                  ----                ----                 -------
  Warning  ChannelReconcileFailed  81s (x21 over 56m)  kafka-ch-controller  KafkaChannel reconciliation failed: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

 **Knative release version**
0.13

 **Additional context**
I test the Kafka instance, it works ok.
