### ISSUE TITLE
kafkasource instance not working with istio-proxy sidecar 

### ISSUE THREAD

**Issue by Shashankft9** [knative/eventing-contrib#1326]
**Describe the bug**
I am trying to impose some Istio authorization policies in the knative working space, hence controlling one of the aspect: selecting which knative service can receive the messages from kafkasource. For this, I need to use mTLS and to inject sidecar into the kafkasource pod. But I notice that as I label the namespace (in which kafkasource instance is running) as `istio-injection=enabled` and restart the pod, this error comes:

```
{"level":"info","ts":"2020-06-18T06:44:22.630Z","caller":"adapter/adapter.go:85","msg":"Starting with config: ","Topics":"testing","ConsumerGroup":"newgroup","SinkURI":"http://datafetch-go.knative-tests.svc.cluster.local","Name":"datafetch-source","Namespace":"default"}
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).start(0xc0000fed50, 0xc0000c84e0, 0x0, 0x0)
        knative.dev/eventing-contrib@/kafka/source/pkg/adapter/adapter.go:103 +0x9ef
knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start(0xc0000fed50, 0x1e088a0, 0xc000682a80, 0x0, 0xc000b15960)
        knative.dev/eventing-contrib@/kafka/source/pkg/adapter/adapter.go:81 +0x3f
knative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext(0x1e092e0, 0xc0005c6488, 0x1a5c9f3, 0xb, 0x1b1a040, 0x1b1a038)
        knative.dev/eventing@v0.15.1-0.20200611131923-68298422e483/pkg/adapter/v2/main_message.go:119 +0xeea
knative.dev/eventing/pkg/adapter/v2.MainMessageAdapter(0x1a5c9f3, 0xb, 0x1b1a040, 0x1b1a038)
        knative.dev/eventing@v0.15.1-0.20200611131923-68298422e483/pkg/adapter/v2/main_message.go:45 +0x92
main.main()
        knative.dev/eventing-contrib@/kafka/source/cmd/receive_adapter/main.go:26 +0x4e
```

 **Expected behavior**
The pod should again start up normally with one additional container of `envoy-proxy`

 **Knative release version**
v0.14.0

**Comment by pierDipi** [comment]
Would you mind providing a reproducible?

**Comment by Shashankft9** [comment]
I first injected the default ns with `istio-injection=enabled` and then created this kafkasource:

```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: datafetch-source
  namespace: default
spec:
  consumerGroup: newgroup
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - testing
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: datafetch-go
      namespace: knative-tests
```

**Comment by Shashankft9** [comment]
@pierDipi I'm wondering that maybe there is no need to run the kafkasource instance with istio-proxy sidecar, could you please tell me the flow of request here? like what pods are responsible here inbetween to send a message from the kafkasource pod to the ksvc?

**Comment by Shashankft9** [comment]
@pierDipi anything on this?

**Comment by pierDipi** [comment]
Sorry for the late reply, pods involved here are: 
  - `kafka-source` `-->` `ingress-gateway` `-->` `ksvc`

If `ksvc` was scaled to 0, the `activator` and the `autoscaler` will scale `ksvc` deployment and then the message reaches the `ksvc`. I'm not super familiar with serving though.

**Comment by pierDipi** [comment]
A diagram of serving architecture is this: https://docs.google.com/drawings/d/1VpOJZ2bj7TsOWjKnhnZK6z39BzF5qdKc5ydOFj1H23E/view. I think you need to join `knative-dev` mailing list to view it.

**Comment by Shashankft9** [comment]
Is there some interaction of `kafka-source` with `cluster-local-gateway`? I notice that whenever I apply a policy on this `cluster-local-gateway`, I get 403 in `kafka-source` deployment while sending the messages. 
I understand that here `kafka-source` is a non-mesh pod and as mentioned here: https://github.com/knative/serving/issues/8364#issuecomment-645904009, for a non-mesh pod the first point of contact is `cluster-local-gatway` ?

**Comment by pierDipi** [comment]
Well, that comment is gold, I think the answer to your question should be: yes, it is.

**Comment by Shashankft9** [comment]
the problem is, as soon as I apply this policy, I start getting 403 errors in the logs. 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: cluster-local-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["knative-serving", "default" ]  # Please set the namespace you want to allow.

```

my `kafka-source` deployment is in `default` namespace. And these are the error logs:

```
{"level":"debug","ts":"2020-06-23T09:50:57.785Z","caller":"adapter/adapter.go:142","msg":"Unexpected status code","status code":403}
{"level":"info","ts":"2020-06-23T09:50:57.785Z","caller":"kafka/consumer_handler.go:83","msg":"Failure while handling a message","topic":"testing","partition":0,"offset":8,"error":"403 Forbidden"}
{"level":"error","ts":"2020-06-23T09:50:57.785Z","caller":"adapter/adapter.go:110","msg":"An error has occurred while consuming messages occurred: ","error":"403 Forbidden","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).start.func2\n\tknative.dev/eventing-contrib@/kafka/source/pkg/adapter/adapter.go:110"}
```

And without this policy all is working fine.
