### ISSUE TITLE
GitHubSource breaks GitLabSource

### ISSUE THREAD

**Issue by makandre** [knative/eventing-contrib#1331]
**Describe the bug**

- I followed the instructions and installed GitLabSource configs to `knative-sources` namespace.  Everything works as expected.
- I then did the same with GitHubSource configs
- Now, new GitLabSource custom resources that I create cannot activate.  The pod fails to start and the following error shows up in the `queue-proxy` container's log

```
{"level":"error","ts":"2020-06-22T13:38:02.070Z","logger":"queueproxy","caller":"queue/main.go:414","msg":"Failed to bring up queue-proxy, shutting down.","knative.dev/key":"andrew/gitlabsource-sample2-g68gr-49dn6","knative.dev/pod":"gitlabsource-sample2-g68gr-49dn6-deployment-5f47b5866f-l69pz","error":"metrics server failed: listen tcp :9090: bind: address already in use","stacktrace":"main.main\n\t/opt/app-root/src/go/src/knative.dev/serving/cmd/queue/main.go:414\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"}
```

 **Expected behavior**

I should be able to have both GitHubSources and GitLabSources working side-by-side

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by makandre** [comment]
The pod can start after manually editing the `K_METRICS_CONFIG` value in the knative service yaml:

From:

```yaml
- name: K_METRICS_CONFIG
  value: >-
    {"Domain":"knative.dev/sources","Component":"gitlab_controller","PrometheusPort":0,"ConfigMap":{}}
```

To:

```yaml
- name: K_METRICS_CONFIG
  value: >-
    {"Domain":"","Component":"gitlab_controller","PrometheusPort":0,"ConfigMap":{}}
```
