### ISSUE TITLE
Allow all namespaces in kubeeventsource

### ISSUE THREAD

**Issue by kelaban** [knative/eventing-contrib#159]
## Expected Behavior
When passing `namespace=""` I expect to be able to gather events from all namespaces

## Actual Behavior
Spec is rejected

## Steps to Reproduce the Problem

  1.  Create kuberneteseventsource with
```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KubernetesEventSource
metadata:
  name: testevents
spec:
  namespace: ""
  serviceAccountName: events-sa
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: testchannel
```

## Additional Info

[Kuberneteseventsource](https://github.com/knative/eventing-sources/blob/d0eb0ef5cb9b34daeb3a55f33943d75c48a30b3d/cmd/kuberneteseventsource/main.go#L47) explicitly block `namespace= ""`

Where as [apimachinery](https://github.com/kubernetes/kubernetes/blob/36049ef914d921f520ccf1d654f7e2644cc243b2/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L279) explicitly defines `NamespaceAll=""`
