### ISSUE TITLE
[0.17] KafkaBinding conversion problems

### ISSUE THREAD

**Issue by aliok** [knative/eventing-contrib#1648]
**Describe the bug**
Getting this on 0.17 branch:
```
"level":"error","ts":"2020-10-27T07:37:16.393Z","logger":"kafka-controller.ConversionWebhook","caller":"controller/controller.go:526","msg":"Reconcile error","error":"custom resource \"kafkabindings.bindings.knative.dev\" isn't configured for webhook conversion", 
```

 **Expected behavior**
No error

 **To Reproduce**
Create a KafkaSource with a `ksvc` sink

 **Knative release version**
0.17
Tried with eventing v0.17.7 and eventing-contrib v0.17.4

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aliok** [comment]
@mattmoor have you seen something like that with KafkaBinding? I think you were using KafkaBinding

**Comment by aliok** [comment]
I think KafkaBinding CRD is missing following: :facepalm:
```
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        name: kafka-source-webhook
        namespace: knative-sources
```
