### ISSUE TITLE
[0.17] Constant reconciliation for KafkaSource when it is created as `v1beta1`

### ISSUE THREAD

**Issue by aliok** [knative/eventing-contrib#1649]
**Describe the bug**
Constant reconciliation for KafkaSource when it is created as `v1beta1`

```
 {"level":"info","ts":"2020-10-27T12:13:04.174Z","logger":"kafka-controller.knative.dev-eventing-contrib-kafka-source-pkg-reconciler-source.Reconciler","caller":"controller/controller.go:520","msg":"Reconcile succeeded. Time taken: 22.018803ms","knative.dev/traceid":"f438352f-8da9-40b4-9e32-524d9d5f2c40","knative.dev/key":"default/kafka-source"}
```

 **Expected behavior**
No constant reconciliation

 **To Reproduce**
Create Kafka topic
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
```

Create `ksvc`
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "5"
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display
```
Create KafkaSource
```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092
  topics:
   - my-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```

 **Knative release version**
Tried with eventing v0.17.7 and eventing-contrib v0.17.4

 **Additional context**

Debugging session with Ville: https://knative.slack.com/archives/CQBKVH4QY/p1603801829059700
