### ISSUE TITLE
Github source CrashLoopBackOff 

### ISSUE THREAD

**Issue by kramvan1** [knative/eventing-contrib#534]
## Expected Behavior
github source pod running state

## Actual Behavior
```
NAME                          READY   STATUS             RESTARTS   AGE
github-controller-manager-0   0/1     CrashLoopBackOff   29         124m
```

```
k logs  -n knative-sources github-controller-manager-0
2019/08/08 16:11:21 Registering Components.
2019/08/08 16:11:21 Adding the GitHub Source controller.
2019/08/08 16:11:21 no matches for kind "Service" in version "serving.knative.dev/v1beta1"
```

## Steps to Reproduce the Problem

  1.  versions > 0.7.0
  2.  check github source pod status
  3.

## Additional Info

Appears to be related to this PR https://github.com/knative/eventing-contrib/commit/c25d3142bddbec38fbee364b8a5857d4a7f43cd7

The service was change to `v1beta1` from `v1alpha1`
but in the CRD for serving it's still `v1alpha1`
https://github.com/knative/serving/releases/download/v0.8.0/serving.yaml

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: "v0.8.0"
  name: services.serving.knative.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.url
    name: URL
    type: string
  - JSONPath: .status.latestCreatedRevisionName
    name: LatestCreated
    type: string
  - JSONPath: .status.latestReadyRevisionName
    name: LatestReady
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].reason
    name: Reason
    type: string
  group: serving.knative.dev
  names:
    categories:
    - all
    - knative
    - serving
    kind: Service
    plural: services
    shortNames:
    - kservice
    - ksvc
    singular: service
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
