### ISSUE TITLE
Allow KafkaChannel to specify sasl 

### ISSUE THREAD

**Issue by barlock** [knative/eventing-contrib#643]
## Expected Behavior
Kafka Sources allow the config of sasl for encrypted traffic and login to a kafka broker. KafkaSources do not.

I'd expect something like this to work.
```yaml
apiVersion: messaging.knative.dev/v1alpha1
kind: KafkaChannel
  spec:
    numPartitions: 1
    replicationFactor: 2 
    net:
      sasl:
        enable: true
        user:
          secretKeyRef:
            name: eventstream
            key: user
        password:
          secretKeyRef:
            name: eventstream
            key: password
      tls:
        enable: true
```
## Actual Behavior
Can't connect KafkaChannels to brokers that require sasl and tls

## Steps to Reproduce the Problem

  1. Create a broker requiring tls and sasl
  2. Try to configure a KafkaChannel to point to it

## Additional Info

`KafkaSource` initializes the sarama client with these options.

https://github.com/knative/eventing-contrib/blob/89b43a1d02a3b15dafacac264bf1fb6e6473ec5d/kafka/source/pkg/adapter/adapter.go#L136

`KafkaChannel` doesn't include them 

https://github.com/knative/eventing-contrib/blob/4f4d1cf090991878d4fcfc61a4f3c7f32075233b/kafka/channel/pkg/dispatcher/dispatcher.go#L258
