### ISSUE TITLE
consumer group stops consuming regularly in Kafka channel dispatcher 

### ISSUE THREAD

**Issue by yuzisun** [knative/eventing-contrib#758]
## Expected Behavior
consumer group stops consuming after sometime 

## Actual Behavior
The consumer stops consuming in mid night every day and we had to restart the service, the Kafka channel status still reports fine

```
kubectl get kafkachannels -n xxx
NAME                         READY   REASON   HOSTNAME                                                        AGE
kf-ents-qc-input             True             kf-ents-qc-input-kn-channel.xxx.svc.cluster.local             27h

kubectl get subscriptions -n xxx
NAME                                       READY   REASON                                AGE
kf-ents-qc-input-es-lacus-out-to-parquet   True                                          27h
```
```
"level":"warn","ts":"2019-11-26T02:02:09.036Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group" 
"level":"info","ts":"2019-11-26T02:02:09.046Z","logger":"controller","caller":"kafka/consumer_handler.go:85","msg":"Stopping Consumer Group Handler, topic: kf-ents-qc-input" 
"level":"info","ts":"2019-11-26T02:02:09.145Z","logger":"controller","caller":"kafka/consumer_handler.go:85","msg":"Stopping Consumer Group Handler, topic: kf-ents-qc-input" 
"level":"info","ts":"2019-11-26T02:02:09.230Z","logger":"controller","caller":"kafka/consumer_handler.go:85","msg":"Stopping Consumer Group Handler, topic: kf-ents-qc-input" 
{"level":"info","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"kafka/consumer_handler.go:80","msg":"Message marked: , timestamp = 2019-11-26 02:01:05.715 +0000 UTC, topic = kf-ents-qc-input"}
"level":"info","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"kafka/consumer_handler.go:85","msg":"Stopping Consumer Group Handler, topic: kf-ents-qc-input"
{"level":"warn","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group","error":"Unable to complete request unexpected HTTP response,
expected 2xx, got 502"}
{"level":"warn","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group","error":"kafka: error while consuming kf-ents-qc-input/0: EOF"
}
{"level":"warn","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group","error":"kafka: error while consuming kf-ents-qc-input/2: EOF"
}
{"level":"warn","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group","error":"kafka: error while consuming kf-ents-qc-input/3: EOF"
}
{"level":"warn","ts":"2019-11-26T02:02:11.568Z","logger":"controller","caller":"dispatcher/dispatcher.go:213","msg":"Error in consumer group","error":"kafka: error while consuming kf-ents-qc-input/1: EOF"
```

## Steps to Reproduce the Problem

  1. Create the Knative Service `es-lacus-out-to-parquet` 
  2. Create the Kafka channel `kf-ents-qc-input` and subscription `kf-ents-qc-input-es-lacus-out-to-parquet`
  3. the consumer group stops consuming after sometime

## Additional Info

**Comment by matzew** [comment]
A few questions here:
* what is the version? (I am current testing this with `master` and `ko apply`. Alternatively you apply a built nightly, like:
```
curl -L "https://storage.googleapis.com/knative-nightly/eventing-contrib/latest/kafka-channel.yaml" \
    | sed 's/REPLACE_WITH_CLUSTER_URL/my-cluster-kafka-bootstrap.kafka:9092/' \
    | kubectl apply --filename -
```
* Define sometime :-)  I have a sample running, that writes message to a kafka channel, and I have a consumer (`ksvc`) that is subscribed to it ... and keeps receiving messages

**Comment by matzew** [comment]
I am running the following example on Openshift 4.2 using our operators (which matches knative 0.9):

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: channel-display
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "3"
    spec:
      containers:
        - image: docker.io/matzew/event-display
---
apiVersion: messaging.knative.dev/v1alpha1
kind: KafkaChannel
metadata:
  name: kafka-channel-two
spec:
  numPartitions: 100
  replicationFactor: 1
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: urbanobservatory-api
spec:
  hosts:
  - api.usb.urbanobservatory.ac.uk
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: urbanobservatory-api
spec:
  hosts:
  - api.usb.urbanobservatory.ac.uk
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.usb.urbanobservatory.ac.uk
    route:
    - destination:
        host: api.usb.urbanobservatory.ac.uk
        port:
          number: 443
      weight: 100
---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: urbanobservatory-event-source
spec:
  image: docker.io/matzew/websocketsource-rhdevelopers 
  args: 
    - '--source=wss://api.usb.urbanobservatory.ac.uk/stream'
    - '--eventType=my.custom.event'
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: kafka-channel-two
---
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: sub1
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: kafka-channel-two
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: channel-display
```

the thing is now running there since 15h: I still receive messages
