### ISSUE TITLE
RBAC issue kafkachannel and broker.spec.config

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#942]
## Expected Behavior

new broker works w/ KafkaChannels

## Actual Behavior

it does not work 

## Additional Info

```
{
  "level": "error",
  "ts": "2020-02-20T11:12:07.538Z",
  "logger": "controller",
  "caller": "broker/reconciler.go:190",
  "msg": "returned an error",
  "commit": "587f4a5",
  "knative.dev/traceid": "2d6ced91-6c4b-414e-a65c-c7a794aa7525",
  "knative.dev/key": "default/default",
  "targetMethod": "ReconcileKind",
  "error": "unable to track changes to the trigger Channel: kafkachannels.messaging.knative.dev is forbidden: User \"system:serviceaccount:knative-eventing:eventing-controller\" cannot list resource \"kafkachannels\" in API group \"messaging.knative.dev\" at the cluster scope",
  "stacktrace": "knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker.(*reconcilerImpl).Reconcile\n\tknative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go:190\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:394\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\tknative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:343"
}
{
  "level": "error",
  "ts": "2020-02-20T11:12:07.538Z",
  "logger": "controller",
  "caller": "controller/controller.go:409",
  "msg": "Reconcile error",
  "commit": "587f4a5",
  "error": "unable to track changes to the trigger Channel: kafkachannels.messaging.knative.dev is forbidden: User \"system:serviceaccount:knative-eventing:eventing-controller\" cannot list resource \"kafkachannels\" in API group \"messaging.knative.dev\" at the cluster scope",
  "stacktrace": "knative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:409\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:395\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\tknative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:343"
}

```

**Comment by matzew** [comment]
I am getting `yes`,  with

```
kubectl auth can-i list kafkachannels.messaging.knative.dev --as system:serviceaccount:knative-eventing:eventing-controller
```

(as well when using the `-n knative-eventing` argument)

**Comment by matzew** [comment]
not just with the `config` filed,  but also with the `channelTemplateSpec`:

```
apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: default
spec:
  channelTemplateSpec:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
```

I am getting the error

**Comment by vaikas** [comment]
can you run the auth command with watch, get and other commands as well?

**Comment by matzew** [comment]
so, just tested the 0.12 - and it works there, so this is a regression with the broker coming in 0.13

**Comment by matzew** [comment]
@vaikas `watch`, `get`,`update`, `patch`  all return `yes`

**Comment by matzew** [comment]
/close

this looks like no longer an issue.

E.g. I did override some of the defaults, like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-default-channel
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: devel
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
      numPartitions: 3
      replicationFactor: 1
```
