### ISSUE TITLE
Requests and limits resources are interchanged when creating a KafkaEventSource

### ISSUE THREAD

**Issue by JosepSampe** [knative/eventing-contrib#970]
**Describe the bug**
Trying to update the resources of a kafkaEventSource, the kafka-controller-manager always log messages like this:
```
{"level":"error","ts":"2020-02-27T13:32:47.402Z","logger":"kafka_controller.kafka-source-controller","caller":"reconciler/kafkasource.go:172","msg":"Unable to create the receive adapter{error 25 0  Deployment.apps \"kafkasource-pywren-event-s-fdcb3364-c6f7-4d66-a58c-3d2f0bbfbf7c\" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: \"1\": must be less than or equal to cpu limit}","knative.dev/controller":"kafka-source-controller","knative.dev/traceid":"75e4bf59-d4b2-4cf5-afa6-2fcc54f98d8b","knative.dev/key":"default/pywren-event-source","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/reconciler.(*Reconciler).reconcile\n\t/home/prow/go/src/knative.dev/eventing-contrib/kafka/source/pkg/reconciler/kafkasource.go:172\nknative.dev/eventing-contrib/kafka/source/pkg/reconciler.(*Reconciler).Reconcile\n\t/home/prow/go/src/knative.dev/eventing-contrib/kafka/source/pkg/reconciler/kafkasource.go:108\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:361\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:310"}
```
After some tests I realized that the values set to the `resources:requests` in my yaml are set to the `resources:limits` of the deployment, and the values set to the `resources:limits` in my yaml are set to the `resources:requests` of the deployment.

So if I want to increase the `resources:limits`, in my yaml I have to set them as `resources:requests`

```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative
  bootstrapServers: IP:PORT
  topics: topic-name
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
  resources:
    requests:
      memory: 512Mi
      cpu: 1000m
```

 **Expected behavior**
Correct resources assignment

 **Knative release version**
<=0.12.1
